export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';

export const START_STREAM = 'PLAY_STREAM';
export const PAUSE_STREAM = 'PAUSE_STREAM';
export const RESUME_STREAM = 'RESUME_STREAM';
export const STOP_STREAM = 'STOP_STREAM';
export const LOADING_STREAM = 'LOADING_STREAM';
export const PLAYING_STREAM = 'PLAYING_STREAM';
